/* eslint-disable @next/next/no-img-element */
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import pokemons from '../pokemons'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Softalabs - Área 51</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
      <Image src="/ciente-studio.png" alt="studio-logo" width={600} height={200} />

        <p className={styles.description}>
          Workshop -{' '}
          <code className={styles.code}>Next.js</code>
        </p>

        <Image src="/oak.gif" alt="studio-logo" width={600} height={500} />

        <div className={styles.grid}>
          {pokemons.map((post) =>
              <a href={`/pokemon/${post.slug}`} className={styles.card} key={post.title}>
              <h2>{post.title}</h2>
              <img src={post.image} alt="pokemon" width={150} height={150} />
            </a>
          )}
        </div>

      </main>

      <footer className={styles.footer}>
        <a
          href="https://softaliza.com.br/"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/ciente-studio.png" alt="Logo Softaliza" width={70} height={20} />
          </span>
        </a>
      </footer>
    </div>
  )
}
